class ParaWelcomeScreen {
    version = QUOT(VN_MF_VERSION);

    class Welcome {
        title = "Welcome to Mike Force";
        /*content = "Structured Text Content";*/
		content[] = {
			"<t align='center' size='1.3'>Welcome to the Mike Force at BRO-NATION!",
			"<br/>",
			"<a href='https://www.patreon.com/BroNation'>Become a Patron</a>",
			" or ",
			"<a href='https://www.paypal.com/donate/?hosted_button_id=UMR3FKVWG6E26'>Donate by Paypal</a></t>",
			"<br/><br/>",
			"<t align='center' size='0.9'>",
			"<a href='https://www.battlemetrics.com/servers/arma3/13211026'>Bro Nation Operations[DEDIBOX]</a>",
			"<br/>",
			"<a href='https://www.battlemetrics.com/servers/arma3/4478492'>Bro Nation WS Ops King of the Dunes</a>",
			"<br/>",
			"<a href='https://www.battlemetrics.com/servers/arma3/12679251'>Bro Nation Modded Ops</a>",
			"<br/><br/>",
			"<a href='https://discord.gg/W6geNfx'>Bro Nation Operations Discord</a>",
			"<br/>",
			"<a href='https://discord.gg/HhH4sZmV54'>Bro Nation Units Discord</a>",
			"<br/>",
			"<a href='https://discord.gg/KwNmfjUK3a'>SOG Prairie Fire Discord</a>",
			"<br/>",
			"<a href='https://discord.gg/WY8G2PZZND'>Western Sahara Discord</a>",
			"<br/><br/>",
			"WARNING: The Enemy(Dac Cong) can be Real Players. Do NOT trust any AI!",
			"<br/>",
			"Downloaded a new mission file today? Then check the CHANGELOG, its the button in the bottom left.",
			"<br/><br/>",
			"If you're new to the server, click the discord link above to get familiar with the community and the server",
			"<br/><br/>",
			"You can report issues on discord as well as jump into comms channels to chat with your favorite members",
			"<br/><br/>",
			"That's all for now!",
			"<br/><br/>",
			"Have fun, and good luck. You'll need it. Enemies can be players too ;)",
			"</t>"
		};
    };

    class Changelog {
        title = "Mike Force - Changelog";
        content[] = {
			"<t align='center' size='1.5' font='RobotoCondensedBold'>Changelog</t>",
			"<br/><br/>",
			"<t align='center' size='1.2'>22nd August 2021 - v18</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Dac Cong Suicide vest, explosion is 5-9 seconds later<br/>",
			"[ADDED]Spike Team to player icon colors in preparation for SOG PF Mike Force update from their Dev Team<br/>",
			"[FIXED]Vehicle ranks points for destroying vehicles<br/>",
			"[ADDED]Rank points for kills, murders, suicides and friendly fire. Dac Cong and GI kills are worth more for PvP aspect<br/>",
			"[CHNGD]Turned back on the vehicle locking system to perform a couple tests related to SOG PF Dev Team advice<br/>",
			"[ADDED]GreenHornets/SatansAngels will be able to unlock vehicles from the pilots seat<br/>",
			"[A-N-R]Added and Removed UID's for various whitelisted teams<br/>",
			"[ADDED]Press Corp is back in action and will be available sometime this week<br/>",
			"[ADDED]SOG Prairie Fire Discord link to welcome screen<br/>",
			"[ADDED]New stats, chopper kills, destruction and hunting<br/>",
			"[CHNGD]Kills, murders, suicide and deaths for the PvP setup with Dac Cong</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>15th August 2021 - v17c</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[FIXED]Killing AI from vehicle can reset rank number of player<br/>",
			"[ADDED]Dead bodies to arsenal cleanup<br/>",
			"[ADDED]Server locking system</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>14th August 2021 - v17</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Custom Chat for each group with color ID<br/>",
			"[ADDED]Custom Ranks system from Private up to General of the Army(28 total)<br/>",
			"[ADDED]Stamina Tweaks for better game play experience<br/>",
			"[ADDED]Play Rewards - every 10 minutes get a 1 rank point thank you from Bro-Nation <br/>",
			"[ADDED]Rank Points for killing AI. 1RP for infantry kill, 2RP for kill from vehicles<br/>",
			"[ADDED]Dac Cong now see their own AA emplacements, HQ supplies and Artillery locations<br/>",
			"[REMOVED]Mike Force from seeing any AA or HQ supplies locations until found by ground forces<br/>",
			"[CHNGD]Satans Angels F4 Phantoms are now a wreck recovery<br/>",
			"[ADDED]Military Police base, spawn location with vehicles, arsenal and refueling<br/>",
			"[CHNGD]Spread out the Pleiku Airfield and added more vehicles throughout all bays<br/>",
			"[CHNGD]CAS birds are now over by the Wolfe Pack at the end of the runway<br/>",
			"[ADDED]Armed Cayuse to Light Helicopters spawn area<br/>",
			"[ADDED]Tiger Force full base with vehicles and Teleporter<br/>",
			"[ADDED]MACV-SOG spawn location with arsenal, duty officer and teleporter<br/>",
			"[ADDED]Teleporter to remaining locations that they were absent<br/>",
			"[ADDED]MACV-SOG, Tiger Force, Military Police and the Gun Range to teleporters<br/>",
			"[UPDATED]Tiger Force Round Team Logo on task roster<br/>",
			"[ADDED]A persistent database section for saving long term data about player stats<br/>",
			"[INFO]UID - Name - Team - Rank - Rank Points are currently saved<br/>",
			"[TWEAKS]Network performance tweaks based on 80 slots with GSP</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>29th July 2021 - v16</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Tiger Force group, round patch, team description<br/>",
			"[ADDED]Tiger Force arsenal, duty officer and spawn location<br/>",
			"[ADDED]Leopard Team supporting code for additions like Tiger<br/>",
			"[START]Converting Ranks for Vehicles from MF to custom rank system<br/>",
			"[CHNGD]Restart times to 0300/0700/1200/1700/2200 EST<br/>",
			"[CHNGD]Restart messages timer to above times<br/>",
			"[ADDED]More UID's for Tiger Force</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>24th July 2021 - v15</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Restart Messages at 20/15/10 and less than 5 minutes left<br/>",
			"[ADDED]No Fire Zone Messages with delay between each<br/>",
			"[UPDATED]MikeForce take POW's to Pleiku prison<br/>",
			"[CHNGD]POW Messages come up as Blue when MF takes a pow<br/>",
			"[FIXED]Group Init missing config variable - CWMF<br/>",
			"[FIXED]Building Overlay Init missing config variable - CWMF<br/>",
			"[ADDED]Ground Loot cleanup around arsenals every 15 minutes<br/>",
			"[CHNGD]Wrecks in water, automatically go to repair<br/>",
			"[ADDED]IDLE RESPAWN category allowing for vehicles to auto respawn once considered idle<br/>",
			"[CHNGD]Bicycles(5min) and mosts(20min) are now in this system<br/>",
			"[CHNGD]All Dac Cong vehicles are now in this system as well</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>20th July 2021 - v13</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]No Fire Zones with custom radius settings to all spawn areas including Dac Cong<br/>",
			"[UPGRD]Add F4 Gunner seat for TeamLocks<br/>",
			"[FIXED]Vehicle Team Lock code ejecting players during seat swithcing, if this happens you are teleported to Green Hornet Spawn<br/>",
			"[ADDED]New Tiger Force and spawn location<br/>",
			"[ADDED]Shooting Range<br/>",
			"[ADDED]Mike Force can capture POWs and send them to Pleiku<br/>",
			"[FIXED]Vehicle Ranks any vehicles for Captain were made Lt required<br/>",
			"[ADDED]Green Hornets Titty Bar with Upstairs private rooms<br/>",
			"[ADDED]Satans Angels Bar and Recreational area<br/>",
			"[UPDATED]Map Markers names and locations for clarity of map<br/>",
			"[CHNGD]Welcome Screen now has Patreon,Discord and A3Units links<br/>",
			"[CHNGD]Reduced snakebite chance from 50 to 10 percent<br/>",
			"[ADDED]More Light Helicopters east of the Cobras toward the Gun Range<br/>",
			"[ADDED]Ambient Radios to spawn areas</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>12th July 2021 - v12</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNGD]Press Corp can now go into all vehicles<br/>",
			"[UPGRD]MACV-SOG can switch teams at any time to increase communication efficiency<br/>",
			"[CHNGD]Arsenal changes for Dac Cong and Civilian Side<br/>",
			"[ADDED]Satans Angels Vehicles</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>10th July 2021 - v12</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]10 more slots and more RAM to the server<br/>",
			"[UPGRD]Press Corp to 5 slots for more specatators<br/>",
			"[ADDED]MACV-SOG Command, here is where cross team communication and organization begins<br/>",
			"[ADDED]Black Horse 11th ACAV Regiment<br/>",
			"[UPGRD]Team Selection page to show MACV-SOG, Satans Angels and Black Horse<br/>",
			"[TESTING]Mike Force's ability to take Dac Cong POWs, for now they are sent to the tunnels like MF currently</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>7th July 2021 - v11</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Take Prisoner to the Dac Cong Commandos<br/>",
			"[ADDED]Become Prisoner to the MikeForce Teams<br/>",
			"[ADDED]PressCorp(Spectator) Slot, these are reserved slots like Dac Cong<br/>",
			"[CHNGD]Spawn positions for the POWs that get sent to the tunnels<br/>",
			"[FIXED]Dac Cong team being able to choose Mike Force teams from Duty Officer<br/>",
			"[FIXED]Dac Cong team join code for smooth entry into the slots<br/>",
			"[FIXED]Server writing ranks to player was rewritten to check first for difference in ranks<br/>",
			"[ADDED]Debug for the buildables due to error that pops on server restart(hopefully getting the data needed before mission reset)</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>5th July 2021 - v10d</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[MAP]Closed off all exit holes in 1 of the large tunnel systems<br/>",
			"[MAP]Added arsenal crates to the 4 war rooms for use after breaking free from the cell<br/>",
			"[MAP]Added gates at the exits to teleport you out, should you make it<br/>",
			"[MAP]Follow the arrows, dont follow the arrows. The choice is yours.</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>4th July 2021 - v10b-c</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[HAPPY]Fourth of July to all that celebrate this holiday<br/>",
			"[FIXED]Gunner Name when player is on Static Weapons<br/>",
			"[FIXED]New players with no save rank or team entries will now start a fresh base of PRIVATE and MikeForce<br/>",
			"[CHNGD]All GRID markers ALPHA channel lowered for clarity of map<br/>",
			"Cleaned up some unused code and tweaked a few others</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>3nd July 2021 - v10</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGRD]Icon color structure MikeForce:BLUE ACAV:ORANGE GreenHornets/SatansAngels:GREEN<br/>",
			"[INFO]Vehicle Icon color will follow the driver or pilots group color above<br/>",
			"[CHNGD]All static weapons can be used by rank PRIVATE and above<br/>",
			"[CHNGD]All trucks for repair/refuel/rearm at Pleiku Airfield are now assigned to ACAV instead of GreenHornets<br/>",
			"[UPGRD]Dac Cong can no longer spawn at MikeForce Captured Objectives<br/>",
			"[ADDED]Server will now save both your last Team and Rank<br/>",
			"[ADDED]Server loads players last team and spawns them in the appropriate base<br/>",
			"[ADDED]Server loads players last rank allowing upper ranked vehicles to be used</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>2nd July 2021 - v9</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Jeeps and Choppers to Pleiku Airfield<br/>",
			"[ADDED]Another Boat at dock and all boats can be driven by rank PRIVATE and above<br/>",
			"[CHNGD]Most vehicles can be driven by rank PRIVATE and above<br/>",
			"[SWAPPED]T63 for another Bulldog<br/>",
			"[CHNGD]Vehicles with pilot guns/missles are left with ranks<br/>",
			"[CHNGD]F4 does not require rank for SatansAngels Squadron Members<br/>",
			"[CHNGD]Zones alpha color reduced to 0.7</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>1st July 2021 - v7d</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGRD]Server restarts every 4 hours starting at 0200 hours(Eastern Time Zone)</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Whitelisted arsenal enabled</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNGD]Ranks enabled</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNGD]Many items locked to their appropriate sides</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGRD]Rewrote map player/vehicle markers to delete opposite teams markers if they are there</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[FIXED]Satans Angels spawn code</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNGD]Locking system is turned back off again</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>30th June 2021 - v7b</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Left shoulder insignia system, help us get a upgraded dedicated server!</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>  -Donate to have your groups UIDs added for your left shoulder insignia added(more to come)</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[FIXED]Dac Cong UID array issue</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Real Dac Cong PRU vietnam war patch for team menu</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ISSUE]Players joining the server with restricted assets or workshop mod items in their saved loadouts</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>  -All players must goto the arsenal and load a saved loadout from their profile</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Custom settings system starting with the Mike Force auto locking system</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNGD]Turn Off Vehicle Locking System</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]TeamKills are now logged. Data will be evaluated for resolutions.</t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>28th - 29th June 2021 - v7a</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]SatansAngels / DacCong / Leopard UIDs</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Satans Angels 433rd Tactical Fighter Squadron</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNG]Satans Angels will be allowed to pilot the F4 Phantom as intended</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[FIX]Vehicle markers of Dac Cong showing up for Mike Force teams</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[REMOVED]Dac Cong Chopper with Rockets</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGR]Dac Cong vehicles are now locked to Dac Cong Players</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Many new Dac Cong Players UIDs are now approved</t><br/>",
			"<t align='center' font='RobotoCondensedLight'> [] </t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>21st - 26th June 2021 - v6(a-d)</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGR]Welcome screen Clickable Discord link added</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNG]H and N menus now require alt keypress : ALT+H or ALT+N</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[CHNG]ALL Duty Officers should now face towards you the player</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Dac Cong Enemy Team with Playable Slots and Friendly AI</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]DC Base, Vehicles, Teleporters, Arsenal, Duty/Supply Officers</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[FIXED]Map Markers isolated by team so enemies do not see each other</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Player Icons are now based on training at Duty Officer</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[UPGR]Infantry, Medical, Maintenance(engineer), Ordnance(explosives), Artillery</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Reserved team slots system added for Dac Cong and Leopard Ops Team</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[NEW]Dac Cong Applications accepted and added to reserved team slots</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>[ADDED]Leopard Ops Team and Reserved Slots(Future Upgrades coming)</t><br/>",
			"<t align='center' font='RobotoCondensedLight'> [] </t><br/>",
			"<br/><br/>",
			"<t align='center' size='1.2'>7th May 2021 - v0.65.03</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>Added 3 headless client slots</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>Scaled up the task roster</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>Added parameter to change the AI limit</t><br/>",
			"<br/>",
			"<t align='center' size='1.2'>7th May 2021 - v0.65.02</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>Reduced the mission to 32 slots (the number the mission is designed for)</t><br/>",
			"<br/>",
			"<t align='center' size='1.2'>6th May 2021 - v0.65.00</t><br/>",
			"<t align='center' font='RobotoCondensedLight'>Initial Beta Release</t>"
		};
    };
};